---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define mysql_daemon.
  set_fact:
    mysql_daemon: "{{ __mysql_daemon }}"
  when: mysql_daemon is not defined

- name: Define mysql_datadir.
  set_fact:
    mysql_datadir: "{{ __mysql_datadir }}"
  when: mysql_datadir is not defined

- name: Define mysql_log_error.
  set_fact:
    mysql_log_error: "{{ __mysql_log_error }}"
  when: mysql_log_error is not defined

- name: Define mysql_pid_file.
  set_fact:
    mysql_pid_file: "{{ __mysql_pid_file }}"
  when: mysql_pid_file is not defined

- name: Define mysql_slow_query_log_file.
  set_fact:
    mysql_slow_query_log_file: "{{ __mysql_slow_query_log_file }}"
  when: mysql_slow_query_log_file is not defined

- name: Define mysql_syslog_tag.
  set_fact:
    mysql_syslog_tag: "{{ __mysql_syslog_tag }}"
  when: mysql_syslog_tag is not defined

- name: Define mysql_packages.
  set_fact:
    mysql_packages: "{{ __mysql_packages | list }}"
  when: mysql_packages is not defined

- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ mysql_install is defined and mysql_install.changed }}"
  when: mysql_setup_server

- include: configure.yml
  when: mysql_setup_server
- include: secure.yml
  when: mysql_setup_server
- include: databases.yml
  when: mysql_setup_server
- include: users.yml
  when: mysql_setup_server
- include: replication.yml
  when: mysql_setup_server
