---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: define mysql_service_name
  set_fact: mysql_service_name={{ __mysql_service_name }}
  when: mysql_service_name is not defined

- name: define mysql_packages
  set_fact: mysql_packages="{{ __mysql_packages | list }}"
  when: mysql_packages is not defined

- name: define mysql_cnf_log_error
  set_fact: mysql_cnf_log_error={{ __mysql_cnf_log_error }}
  when: mysql_cnf_log_error is not defined

- name: define mysql_cnf_pid_file
  set_fact: mysql_cnf_pid_file={{ __mysql_cnf_pid_file }}
  when: mysql_cnf_pid_file is not defined

- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: copy mysql my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
  when: mysql_cnf_use_template and mysql_setup_server
  notify: restart mysql

- name: start and enable mysql
  service: name={{ mysql_service_name }} state=started enabled=yes
  when: mysql_setup_server

- include: secure.yml
  when: mysql_setup_server

- name: create mysql databases
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
  with_items: mysql_create_databases
  when: mysql_setup_server

- name: create mysql users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: present
  with_items: mysql_create_users
  when: mysql_setup_server
