---
- name: define mysql_enablerepo
  set_fact: mysql_enablerepo={{ __mysql_enablerepo }}
  when: mysql_enablerepo is not defined

- name: install mysql packages
  yum: name={{ item }} state=present enablerepo={{ mysql_enablerepo }}
  with_items: mysql_packages
  register: mysql_install
